pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                echo "Listing workspace files..."
                bat "dir"

                echo "Running Maven Wrapper..."
                bat "mvnw.cmd clean compile"
            }
        }
    }

    post {
        success {
            echo "✅ BUILD SUCCESS"
        }
        failure {
            echo "❌ BUILD FAILED"
        }
    }
}
